/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package aoc2024

import java.io.File
import java.io.Reader

fun main(args: Array<String>) {
    when (args[0]) {
        "1" -> runDay01()
        "2" -> runDay02()
        "3" -> runDay03()
        "4" -> runDay04()
        /*
        "5" -> runDay05()
        "6" -> runDay06()
        "7" -> runDay07()
        "8" -> runDay08()
        "9" -> runDay09()
        "10" -> runDay10()
        "11" -> runDay11()
        "12" -> runDay12()
        "13" -> runDay13()
        "14" -> runDay14()
        "15" -> runDay15()
        "16" -> runDay16()
        */
        else -> println("""
            https://adventofcode.com/2024/
            
            Usage: App day-number
            
            Inputs are assumed to be in 'inputs/2024/NN.txt' where 'NN' is the 2-digit day number.
            If the file isn't present, it reads from stdin instead.
            """.trimIndent())
    }
}

fun runDay01() {
    println("Part 1: " + totalListDistance(inputLines(1)))
    println("Part 2: " + similarityScore(inputLines(1)))
}

fun runDay02() {
    println("Part 1: " + inputLines(2).count { isLevelSafe(inputLineAsIntList(it)) })
    println("Part 2: " + inputLines(2).count { isDampenedLevelSafe(inputLineAsIntList(it)) })
}

fun runDay03() {
    println("Part 1: " + cleanAndExecute(inputAsText(3)))
    println("Part 2: " + cleanAndExecuteWithConditions(inputAsText(3)))
}

fun runDay04() {
    println("Part 1: " + countXmases(inputLines(4)))
    println("Part 2: " + countCrossMases(inputLines(4)))
}

fun inputForDay(dayNum: Int): Reader = File(String.format("inputs/2024/%02d.txt", dayNum))
    .let { if (it.exists()) it.bufferedReader() else System.`in`.bufferedReader() }

fun inputLines(dayNum: Int): List<String> = inputForDay(dayNum).readLines()

//fun inputAsIntList(dayNum: Int) = inputLines(dayNum).map { it.toInt() }

fun inputLineAsIntList(line: String) = line.split(" ").map { it.toInt() }

//fun inputAsLongList(dayNum: Int) = inputLines(dayNum).map { it.toLong() }

fun inputAsText(dayNum: Int) : String = inputForDay(dayNum).readText()