/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package aoc2025

import java.io.File
import java.io.Reader

fun main(args: Array<String>) {
    when (args[0]) {
        "1" -> runDay01()
        "2" -> runDay02()
        "3" -> runDay03()
        "4" -> runDay04()
        "5" -> runDay05()
        "6" -> runDay06()
        "7" -> runDay07()
        "8" -> runDay08()
//        "9" -> runDay09()
//        "10" -> runDay10()
//        "11" -> runDay11()
//        "12" -> runDay12()
//        "13" -> runDay13()
//        "14" -> runDay14()
//        "15" -> runDay15()
//        "16" -> runDay16()
        else -> println("""
            https://adventofcode.com/2025/
            
            Usage: App day-number
            
            Inputs are assumed to be in 'inputs/2025/NN.txt' where 'NN' is the 2-digit day number.
            If the file isn't present, it reads from stdin instead.
            """.trimIndent())
    }
}

fun runDay01() {
    println("Part 1: " + numberOfStopsOnZero(inputLines(1)))
    println("Part 2: " + numberOfPassesThroughZero(inputLines(1)))
}

fun runDay02() {
    println("Part 1: " + sumOfInvalidIdsInRangeData(inputAsText(2)))
    println("Part 1: " + sumOfInvalidIdsInRangeData(inputAsText(2), ID2_PATTERN))
}

fun runDay03() {
    println("Part 1: " + totalJoltageOfBanks(inputLines(3)))
    println("Part 2: " + totalJoltageOfBanks(inputLines(3), 12))
}

fun runDay04() {
    println("Part 1: " + countAccessibleRolls(inputLines(4)))
    println("Part 2: " + countRemovedRolls(inputLines(4)))
}

fun runDay05() {
    println("Part 1: " + countFreshIngredients(inputLines(5)))
    println("Part 2: " + totalPossibleFreshIngredients(inputLines(5)))
}

fun runDay06() {
    println("Part 1: " + solveWorksheet(inputLines(6)))
    println("Part 2: " + solveWorksheetTopToBottom(inputLines(6)))
}

fun runDay07() {
    println("Part 1: " + tachyonSplitterCount(inputLines(7)))
    println("Part 2: " + tachyonPathCount(inputLines(7)))
}

fun runDay08() {
    println("Part 1:" + circuitCalculation(inputLines(8), 1000))
}

fun inputForDay(dayNum: Int): Reader = File(String.format("inputs/2025/%02d.txt", dayNum))
    .let { if (it.exists()) it.bufferedReader() else System.`in`.bufferedReader() }

fun inputLines(dayNum: Int): List<String> = inputForDay(dayNum).readLines()

//fun inputAsIntList(dayNum: Int) = inputLines(dayNum).map { it.toInt() }

//fun inputLineAsIntList(line: String) = line.split(" ").map { it.toInt() }

//fun inputAsLongList(dayNum: Int) = inputLines(dayNum).map { it.toLong() }

fun inputAsText(dayNum: Int) : String = inputForDay(dayNum).readText()