package aoc2024

import io.kotest.core.spec.style.FunSpec
import io.kotest.matchers.shouldBe

class Day2408Spec : FunSpec ({
    val example = """
        ............
        ........0...
        .....0......
        .......0....
        ....0.......
        ......A.....
        ............
        ............
        ........A...
        .........A..
        ............
        ............""".trimIndent()

    test("count antinodes") {
        uniqueAntinodes(example.split("\n")).shouldBe(14)
    }

    test("count extended antinodes") {
        uniqueAntinodesExtended(example.split("\n")).shouldBe(34)
    }
})